sudo: required

language: bash

services:
  - docker

before_install:
  - docker pull koalaman/shellcheck

script:
  - echo "#!/bin/bash" > .env
  - docker run --rm -v $(pwd):/scripts -w /scripts koalaman/shellcheck -x .env run.sh

matrix:
  fast_finish: true
